### ISSUE TITLE
proplem

### ISSUE THREAD

**Issue by FozexD** [Podshot/MCEdit-Unified-Preview#1]
i just moved a bulding to my new world in the mcedit i see it all fine when i paste it there but when i go in minecraft the top of it is not fine like if there was some height limit please help

**Comment by Podshot** [comment]
Please submit your issue [here](https://github.com/Khroki/MCEdit-Unified/issues) with a screenshot of the console window, your log file, and the OS you're using. This issue page is only for bugs that are directly related to launching MCEdit-Unified testing releases.
