### ISSUE TITLE
Cannot Open , crash

### ISSUE THREAD

**Issue by JustFragger** [Podshot/MCEdit-Unified-Preview#21]
Hello !
All version of mcedit , and this testing crash on my pc , just open cmd console and nothing crash 
no log fiel just nothing I"m using windows 1903 .

**Comment by Daniel34M** [comment]
I am having the same issue :(

**Comment by JustFragger** [comment]
> I am having the same issue :(

Hey Daniel !
I"m not using anymore this mcedit unified just go to mcedit.net and download mcedit BETA6 , because BETA14 doesnt work idk whyy but BETA 6 WORKED for me so you can try it

**Comment by Daniel34M** [comment]
Thanks! I'll try to use it!

**Comment by JustFragger** [comment]
Okay so I fixxed my problem So I"m closing this thread .
